name: mygenericbinder2
channels:
  - defaults
  - conda-forge
dependencies:
  - ipykernel
  - python=3.7
  - pip
  - pip:
    - pathtools==0.1.2
    - streamlit
    - jupyter-server-proxy
    - nbserverproxy  
    - nbgitpuller
    - datetime
    - random2
    - bokeh
    - markdown
    - numpy
    - scipy
    - matplotlib
    - pandas
    - vega
    - pyaudio
    - nbconvert
